version: '3'

services:
    app:
        build: .
        container_name: app
        restart: always
        entrypoint: dockerize -wait tcp://db:3306 -timeout 20s php-fpm
        volumes:
            - .:/var/www
        networks:
            - laravel-network
        depends_on:
          - db
    nginx:
        build: .docker/nginx
        container_name: nginx
        restart: always
        tty: true
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
        networks:
            - laravel-network
        depends_on:
          - app
    redis:
        image: redis:6.0.3-alpine
        restart: always
        expose:
            - 6379
        networks:
            - laravel-network
    db:
        image: mysql:5.7
        command: --innodb_use_native_aio=0
        expose:
            - 3306
        environment:
            - MYSQL_ROOT_PASSWORD=app
            - MYSQL_DATABASE=laravel
        volumes:
            - .docker/db/data:/var/lib/mysql
        networks:
            - laravel-network

networks:
    laravel-network:
        driver: bridge
